HW2 is completed
khaydarov/otus-golang-professional pull request #3
Opened 2023-12-06 10:03 UTC by khaydarov

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-12-06 15:46 UTC, hungry-honeybadger requested changes
Хорошее начало. Круто что решение сходу проходит все базовые тесты. Но у работы есть проблемы с многобайтовыми кодировками. Для отладки проблемы можно использовать любой тест кейс с кириллицей. Например `{input: "cб2l", expected: "cббl"},`

2023-12-06 15:46 UTC, hungry-honeybadger commented on hw02_unpack_string/unpack.go
> +	for i := 0; i < len(s); i++ {
В golang со строками нельзя работать с помощью такого цикла for, так как когда идет обращение по индексу, то адресуется не весь символ а его первый байт. Поэтому тесты с однобайтовой кодировкой проходят без проблем, но если попробовать использовать многобайтовую кодировку например кириллицу, то будут проблемы

2023-12-07 09:05 UTC, khaydarov commented on hw02_unpack_string/unpack.go
> +	for i := 0; i < len(s); i++ {
Учел этот момент, спасибо!

2023-12-07 10:33 UTC, vladislavmass requested changes

2023-12-07 10:33 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +			if len(s)-1 == i {
Проверять на каждой итерации что символ не последний это не самая лучшая идея. Лучше обработать эту ситуацию после блока for.

2023-12-07 10:33 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +			if len(s)-1 == i {
Так же тут есть обращение по индексу что приводит к проблемам в кейсах где последний символ является многобайтовым. Для примера такой тест кейс `{input: "a2bccdб", expected: "aabccdб"},`

2023-12-07 13:55 UTC, khaydarov commented on hw02_unpack_string/unpack.go
> +			if len(s)-1 == i {
Классный тесткейс. Пофиксил.

2023-12-08 06:55 UTC, vladislavmass approved these changes
Хорошая работа. Принято

2023-12-08 07:05 UTC, merged