HW4 is completed
khaydarov/otus-golang-professional pull request #7
Opened 2023-12-21 19:44 UTC by khaydarov

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-12-21 19:49 UTC, khaydarov commented on hw04_lru_cache/cache.go
> +		for k, v := range c.items {
Сразу обращу внимание на этот фрагмент кода. 
Здесь не обойти карту и удалить из items нужный элемент не получиться так как мы из связного списка получаем только `*ListItem`, а удалить можем только по `Key` => `delete(c.items, key)`. Поэтому нам придется пробежаться по карте и по *ListItem найти этот ключ.

Чтобы получить O(1) вижу два варианта:
1) создать две карты - map[Key]*ListItem и map[*ListItem]Key
2) В структуру ListItem добавить рядом с Value значение Key.

2023-12-21 20:06 UTC, vladislavmass requested changes
Хорошее начало, но есть несколько мест с потенциальной паникой

2023-12-21 20:06 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	case l.front:
Если мы из списка решим удалить единственный элемент, то получим панику

2023-12-21 20:06 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.back == i {
Тут тоже будет паника если в листе всего 1 элемент

2023-12-21 20:06 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +		for k, v := range c.items {
2 вариант вполне рабочий

2023-12-25 13:49 UTC, vladislavmass approved these changes
Хорошая работа. Принято

2023-12-25 14:01 UTC, merged