HW5 is completed
khaydarov/otus-golang-professional pull request #8
Opened 2024-01-08 13:31 UTC by khaydarov

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-01-08 14:08 UTC, vladislavmass requested changes

2024-01-08 14:08 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +	if atomic.LoadInt32(&countOfErrors) >= maxErrorCount {
Тут атомик уже не нужен так как тут возможно обращение только из 1 потока

2024-01-08 14:08 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +	tasksChannel := make(chan Task, len(tasks))
Если в слайсе будет 1 млн тасков, то мы создадим буфер в 1 млн тасков. Это не очень эффективная по памяти история

2024-01-08 14:08 UTC, vladislavmass commented on hw05_parallel_execution/go.mod
> +module github.com/khaydarovm/hw05_parallel_execution
Неверное имя модуля

2024-01-09 06:17 UTC, khaydarov commented on hw05_parallel_execution/run.go
> +	tasksChannel := make(chan Task, len(tasks))
Понял, спасибо за замечание

2024-01-09 06:31 UTC, vladislavmass requested changes
Хорошая работа. Но в коде есть потенциальная паника

2024-01-09 06:31 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +		err := task()
Если task==nil, то тут будет паника

2024-01-09 07:09 UTC, khaydarov commented on hw05_parallel_execution/run.go
> +		if atomic.LoadInt32(&countOfErrors) >= maxErrorCount {
здесь была гонка, починил всплепую, не понял решение сам

2024-01-09 07:42 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +	ctx, cancel := context.WithCancel(context.Background())
Эта история в данном случае вообще не нужна. Мы выйдем из range for chanel по закрытию канала

2024-01-09 07:42 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +			if atomic.LoadInt32(countOfErrors) >= maxErrorCount {
Блок кода с 72 по 75 строку не имеет смысла. Так как мы пытаемся отловить ошибку которая произошла между чтением из канала и запуском таска.

2024-01-09 07:42 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +		select {
Тут лучше все таки было использовать range по каналу.

2024-01-10 06:50 UTC, vladislavmass approved these changes

2024-01-10 11:49 UTC, merged